# Nginx
- name: Install nginx
  apt: name=nginx state=latest update_cache=yes

- name: Remove default nginx default
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Generate dhparams file
  shell: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048

# Lets encrypt
- name: Install dependencies
  apt: name={{ item }} state=latest
  loop: ['python', 'python-dev', 'gcc', 'dialog', 'libaugeas0', 'augeas-lenses', 'libssl-dev', 'libffi-dev', 'ca-certificates', 'python-pip', 'python-virtualenv', 'git', 'libpython-dev', 'zlib1g-dev']

- name: Lets Encrypt client
  git: dest=/opt/certbot clone=yes repo=https://github.com/certbot/certbot force=yes

# Auto-renew certificates and reload nginx
- name: Add crontab to renew certificates
  cron:
    name: "renew certificates (antoinechalifour.dev)"
    state: present
    minute: "30"
    hour: "2"
    weekday: "1"
    job: "/opt/certbot/certbot-auto renew >> /var/log/le-renew.log"

- name: Add crontab to reload server
  cron:
    name: "reload nginx (antoinechalifour.dev)"
    state: present
    minute: "35"
    hour: "2"
    weekday: "1"
    job: "/etc/init.d/nginx reload"

# Nginx Configuration
- name: Add http nginx configuration
  template: src=http.conf.j2 dest=/etc/nginx/sites-available/{{ service_name }}.http.conf owner=www-data group=www-data mode=0644

- name: Add http nginx symlink
  file: src=/etc/nginx/sites-available/{{ service_name }}.http.conf dest=/etc/nginx/sites-enabled/{{ service_name }}.http owner=www-data group=www-data state=link

- name: reload nginx
  service: name=nginx state=reloaded

# FIXME: WARNING: this is not idempotent. Do not forget to uncomment if you need certificates
#- name: Create certificate
#  shell: ./certbot-auto certonly --webroot --email {{ service_admin_email }} --agree-tos --webroot-path=/usr/share/nginx/html -d {{ service_host }};
#  args:
#    chdir: /opt/certbot

- name: Add https nginx configuration
  template: src=https.conf.j2 dest=/etc/nginx/sites-available/{{ service_name }}.https.conf owner=www-data group=www-data mode=0644

- name: Add external https nginx symlink
  file: src=/etc/nginx/sites-available/{{ service_name }}.https.conf dest=/etc/nginx/sites-enabled/{{ service_name }}.https owner=www-data group=www-data state=link

- name: reload nginx
  service: name=nginx state=reloaded